### ISSUE TITLE
Hey Buddy just cloned your repository but I am seeing a blank black screen on the window after running and nothing else can u help me with this

### ISSUE THREAD

**Issue by aadipoddar** [Shturm0weak/OpenGL_Engine#3]
![image](https://user-images.githubusercontent.com/83405769/128225253-1eede08d-4f93-4301-8988-442e3c62f7c5.png)

**Comment by aleksandrturlak** [comment]
Man, I am sorry that I reply so late, I rarely check this page.
Shaders can't be compiled, can I know your pc specs?

**Comment by aadipoddar** [comment]
So sorry I just saw your Reply.


Processor	Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz   1.80 GHz
Installed RAM	8.00 GB (7.86 GB usable)
System type	64-bit operating system, x64-based processor

**Comment by aleksandrturlak** [comment]
lol, so long time.
I have just checked your GPU, so it is obvious that it can't be compiled, because your intel hd 620 supports only OpenGl 4.4, when this project is built with OpenGl 4.6 (my assumptions).
It seems that I have to recompile this project with an older version actually : )
My new project (Pengine) is built with an older version, you can check it out.
